name: Deploy

on:  
  workflow_dispatch:
  schedule:
  - cron: '45 09 * * *'  #every day at 3:15 pm IST

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Set up Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: '3.x'
          cache: 'pip'
      - name: Wait for Test
        uses: fountainhead/action-wait-for-check@v1.1.0
        with:
          checkName: test
          token: ${{ github.token }}
      - name: Install virtual display dependencies
        run: sudo apt install -y xvfb
      - name: Install python dependencies
        run: pip install -r requirements.txt
      - name: Run Script
        run: timeout 2160 python MicrosoftRewardsBot.py --accounts ${{ secrets.ACCOUNTS }} --headless --fast
      
